export const Textos = {
    EXITO: "Usuario creado con éxito",
    ERROR: "No se pudo crear el usuario",
    EXITO_MODIFICAR: "Usuario modificado con éxito",
    ERROR_MODIFICAR: "No se pudo modificar el usuario",
    EXITO_BORRAR: "Usuario eliminado con éxito",
    ERROR_BORRAR: "No se pudo eliminar el usuario", 
    ERROR_CORREO: "El correo del usuario es incorrecto",
    ERROR_APELLIDO: "El apellido del usuario es incorrecto",
    ERROR_NOMBRE: "El nombre del usuario es incorrecto",
    ERROR_CLAVES: "Las claves especificadas no coinciden o son incorrectas",
    ERROR_PERFIL: "El perfil del usuario es incorrecto",
    PERFIL_CAMBIO: "El usuario no puede cambiarse de perfil",
    ERROR_PERMISOS: "No se tienen los permisos para realizar esta funcionalidad",
    USUARIOS_DUPLICADOS: "Ya existe un usuario con ese correo",
    USUARIO_INEXISTENTE: "No existe el usuario especificado",
    VALIDACION_EXITO: "Los datos del usuario son correctos",
    ERROR_CONTRASENIA: "La clave es incorrecta",
    ERROR_DNI: "El DNI del usuario es inválido",
    ERROR_TELEFONO: "El telefono de contacto del usuario es inválido",
    ERROR_OBRASOCIAL: "El campo seleccionado no es válido",
    ERROR_NOPOSEO: "Campos de obra social incoherentes"
};