export const ESPECIALIDADES = {
    MEDICINA_GENERAL: 'Medicina General',
    PEDIATRIA: 'Pediatría',
    CIRUGIA: 'Cirugía',
    OFTALMOLOGIA: 'Oftalmología',
    CARDIOLOGIA: 'Cardiología',
    OFTALMOLOGIA: 'Oftalmología',
    GINECOLOGIA: 'Ginecología',
    OBSTETRICIA: 'Obstetricia',
    TRAUMATOLOGIA: 'Traumatología',
    OTORRINONARINGOLOGIA: 'Otorrinonaringología',
    GASTROENTEROLOGIA: 'Gastroenterología',
    DERMATOLOGIA: 'Dermatología',
    ONCOLOGIA: 'Oncología',
  }